27th Aug 2021/Employees/Employees/Controllers/SkillsController.cs
using Employees.Data;
using Employees.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Employees.Controllers
{
    public class SkillsController : Controller
    {
        private readonly MyDbContext _db;

        public SkillsController(MyDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Skills> skill = _db.skill;

            return View(skill);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]

        public IActionResult Create(Skills skill)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _db.skill.Add(skill);
                    _db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }
            
            catch
            {
                ViewBag.Duplicate = skill.SkillName + " skill already exists";
            }

            return View(skill);
        }

        public IActionResult Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skill = _db.skill.FirstOrDefault(x => x.SkillId == id);
            if (skill == null)
            {
                return NotFound();
            }

            return View(skill);
        }

        [HttpPost]
        public IActionResult Update(Skills skill)
        {
            if (ModelState.IsValid)
            {
                _db.skill.Update(skill);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(skill);
        }


        public IActionResult Delete(int? id)
        {
            var skill = _db.skill.FirstOrDefault(x => x.SkillId == id);

            if (skill == null)
            {
                return NotFound();
            }
            _db.skill.Remove(skill);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

27th Aug 2021/Employees/Employees/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employees</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employees</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Skills" asp-action="Index"> Skill List </a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Employees - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

27th Aug 2021/Employees/Employees/Views/Shared/_Login.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<EmployeeUser> signInManager
@if (signInManager.IsSignedIn(User))
{
    <form method="post" id="logoutForm" asp-action="LogOff" asp-controller="Frontpage">
        <ul class="nav navbar-nav">
            <li class="text-dark nav-link">Hello, @User.Identity.Name! </li>
            <li><a class=" nav-link  text-dark" href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav">
        <li class="nav-item">
            @*@Html.ActionLink("Sign Up", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })*@
            <a class="nav-link  text-dark" id="registerLink" asp-controller="Frontpage" asp-action="Register">Register</a>
        </li>
        <li>
            @*@Html.ActionLink("Sign In", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })*@
            <a class="nav-link  text-dark" id="loginLink" asp-controller="Frontpage" asp-action="Login">Sign In</a>
        </li>
    </ul>
}