EmployeeDetails/EmployeeDetails/Controllers/DepartmentController.cs
using EmployeeDetails.Data;
using EmployeeDetails.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeDetails.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly MyDbContext _db;

        public DepartmentController(MyDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<DepartmentDetails> departments = _db.Department;

            return View(departments);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        
        public IActionResult Create(DepartmentDetails dept)
        {
            if (ModelState.IsValid)
            {
                _db.Department.Add(dept);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(dept);
        }
    }
}

EmployeeDetails/EmployeeDetails/Controllers/EmployeeController.cs
using EmployeeDetails.Data;
using EmployeeDetails.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EmployeeDetails.Controllers
{
    public class EmployeeController : BaseController<EmployeesDetail>
    {
        private readonly MyDbContext _db;

        public EmployeeController(MyDbContext db)
        {
            _db = db;
        }

        public IActionResult Index(string search = null, int page = 1)
        {
            IEnumerable<EmployeesDetail> employees = _db.Employee.Where(x => x.DelStatus == 'A');

            var paginatedResult = PaginatedResult(employees.ToList(), page, 10);

            return View(paginatedResult);
        }

        [HttpGet]
        public IActionResult Index(string searchText,string sortOrder)
        {
            ViewData["NameSortParam"] = sortOrder == "Name" ? "name_desc" : "name_asc";
            ViewData["DesignationSortParam"] = sortOrder == "Designation" ? "design_desc" : "design_asc";
            ViewData["DateSortParam"] = sortOrder == "HireDate" ? "date_desc" : "date_asc";
            ViewData["CurrentSearch"] = searchText;

            var employee =  from emp in _db.Employee where emp.DelStatus == 'A' select emp;
            if (!string.IsNullOrEmpty(searchText))
            {
                employee = employee.Where(x => x.Name.ToLower().Contains(searchText.ToLower()));
            }

            switch (sortOrder)
            {
                case "name_asc":
                    employee = employee.OrderBy(x => x.Name);
                    break;

                case "name_desc":
                    employee = employee.OrderByDescending(x => x.Name);
                    break;
                case "design_asc":
                    employee = employee.OrderBy(x => x.Designation);
                    break;
                case "design_desc":
                    employee = employee.OrderByDescending(x => x.Designation);
                    break;
                case "date_asc":
                    employee = employee.OrderBy(x => x.HireDate);
                    break;
                case "date_desc":
                    employee = employee.OrderByDescending(x => x.HireDate);
                    break;
                default:
                    employee = employee.OrderBy(x => x.Id);
                    break;

            }
           
            return View(employee.ToList());


        }       

        public IActionResult Create()
        {
            IEnumerable<SelectListItem> listItems = _db.Department.Select(x => 
                 new SelectListItem
                 {
                     Text = x.DepartmentName,
                     Value = x.DepartmentId.ToString()
                 });

            ViewBag.myDropDown = listItems;

            return View();
        }

        [HttpPost]
        public IActionResult Create(EmployeesDetail emp)
        {
            if (ModelState.IsValid)
            {
                _db.Employee.Add(emp);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(emp);
        }

        public IActionResult Update(int? id)
        {
            var emp = _db.Employee.FirstOrDefault(x => x.Id == id);
            IEnumerable<SelectListItem> listItems = _db.Department.Select(x =>
                 new SelectListItem
                 {
                     Text = x.DepartmentName,
                     Value = x.DepartmentId.ToString()
                 });

            ViewBag.myDropDown = listItems;

            return View(emp);
            //if (id == null)
            //{
            //    return NotFound();
            //}

            //var emp = _db.Employee.FirstOrDefault(x => x.Id == id);
            //if (emp == null)
            //{
            //    return NotFound();
            //}

            //return View(emp);
        }

        [HttpPost]
        public IActionResult Update(EmployeesDetail emp)
        {
            if (ModelState.IsValid)
            {
                _db.Employee.Update(emp);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
 
            return View(emp);
        }

        public IActionResult Delete(int? id)
        {
            var emp = _db.Employee.FirstOrDefault(x => x.Id == id);

            if (emp == null)
            {
                return NotFound();
            }
            _db.Employee.Remove(emp);
            _db.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

EmployeeDetails/EmployeeDetails/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeDetails</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EmployeeDetails</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index"> Employee List </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index"> Departments </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EmployeeDetails - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmployeeDetails/EmployeeDetails/Views/Shared/_Pagination.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
    var recordsPerPage = Model;
    var totalRecords = ViewBag.TotalRecords == null ? 0 : ViewBag.TotalRecords;
    int numberOfButtons;
    if (totalRecords % recordsPerPage == 0)
    {
        numberOfButtons = totalRecords / recordsPerPage;
    }
    else
    {
        numberOfButtons = (totalRecords / recordsPerPage) + 1;
    }
}
<ul class="pagination">
    @if (ViewBag.CurrentPage > 1)
    {
        <li>
            <a asp-route-page=@(ViewBag.CurrentPage-1)>Prev</a>
        </li>
    }

    @for (int i = 0; i < numberOfButtons; i++)
    {
        @if (ViewBag.CurrentPage < numberOfButtons)
        {
            <li>
                <a asp-route-page="@(ViewBag.CurrentPage+i)">@(ViewBag.CurrentPage+i)</a>
            </li>
        }
    }
    @if (ViewBag.CurrentPage < numberOfButtons)
    {
        <li>
            <a asp-route-page=@(ViewBag.CurrentPage+1)>Next</a>
        </li>
    }
</ul>

@await Html.PartialAsync("_Pagination", 10)